# Production Configuration for DreamHome Backend
# This file contains production-specific settings

server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: dreamhome-backend
  
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/dreamhome_db?createDatabaseIfNotExist=true&useSSL=true&allowPublicKeyRetrieval=true}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate # Use 'validate' in production to prevent schema changes
    show-sql: false # Disable SQL logging in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-production-secret-key-should-be-very-long-and-secure}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

# File Upload Configuration
file:
  upload:
    dir: ${FILE_UPLOAD_DIR:uploads/}
    max-size: 10MB

# CORS Configuration for Production
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://yourdomain.com,https://www.yourdomain.com}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: "Authorization,Content-Type,Accept,Origin,X-Requested-With,Access-Control-Request-Method,Access-Control-Request-Headers"
  exposed-headers: "Authorization,Content-Disposition"
  allow-credentials: true
  max-age: 3600

# Logging Configuration for Production
logging:
  level:
    com.dreamhome: INFO
    org.springframework.security: WARN
    org.springframework.web.cors: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/dreamhome-backend.log
    max-size: 10MB
    max-history: 30
